### PR TITLE
update in analysis.mk

### PR DESCRIPTION
**Pull request by fabiodepa**
line 62: the -o option of samtools sort will print the sorted bam file in the stdout so I removed it and let only the prefix for the bam file name, samtools sort withount the -o will add the .bam suffinx to the indicated file name.

### CODE REVIEW

**Comment by bsipos** [comment]
Are you using by any chance a very old version of samtools? It should work fine with the latest versions.

**Comment by fabiodepa** [comment]
I am using the docker container build from the Dokerfile in the GitHub. I get the bam on stdout while running the pipeline within the doker container, that's why I think that -o could be the problem.

**Comment by bsipos** [comment]
I see. I have updated the docker image base to latest Ubuntu LTS. Could you build and image and check if it solves the problem?

**Comment by fabiodepa** [comment]
Hi @bsipos 
I tried to do as you suggest rebuilding the docker but it get stucked at some point asking for geographic area... I do not know how to escape from that point. I suppose is a Ubuntu LTS request...

btw this was my first pull request to an existing project on GitHub, I hope I did it the right way...

**Comment by bsipos** [comment]
Hi @fabiodepa 

Thanks for the pull request! It is useful for me to know about this issues.
I have pushed out some changes which should fix the apt-get issue. Could you pleas try to build the image again?

Botond

**Comment by fabiodepa** [comment]
Hi @bsipos 
Sorry for the delay. I attach here the stdout and stderr of the building of the new Dockerfile. 
I had to compile the Dockerfile on a Ubuntu 16.04 LTS because at the moment my Ubuntu 18.04 workstation is out of service... Do you think this could be the porblem?

[stderr.txt](https://github.com/nanoporetech/ont-assembly-polish/files/3093446/stderr.txt)
[stdout.txt](https://github.com/nanoporetech/ont-assembly-polish/files/3093447/stdout.txt)

Fabio

**Comment by bsipos** [comment]
The problem was that the JRE install package I was using is no longer supported. Pushed out a fix, please try building again.

Botond

**Comment by bsipos** [comment]
Hey @fabiodepa ! Does this work for you now?

**Comment by fabiodepa** [comment]
hi @bsipos !
Sorry for the delay... Yes, it works now both the installation and the pipeline, no errors at all!
I think I can close this pull request, correct?
Thanks!

**Pull request closed without merging**
